name: Vitality
main: org.cyberpwn.vitality.Vitality
version: ${project.version}
commands: 
  vitality:
    aliases: [vit, vi]
  vtime: 
    aliases: [time, ti]
  vtp:
    aliases: [teleport, tp]
  vtpall:
    aliases: [teleportall, tpall]
  vtpfall:
    aliases: [teleportforceall, tpfall]
  vtpf:
    aliases: [teleportforce, tpf]
  vtphere: 
    aliases: [teleporthere, tphere, tph]
  vtpfhere: 
    aliases: [teleporthereforce, tpfhere, tpfh]
  vgamemode:
    aliases: [gamemode, gm, g]
  vgms:
    aliases: [gms]
  vgmc:
    aliases: [gmc]
  vgma:
    aliases: [gma]
  vgmsp:
    aliases: [gmsp, spectator, spec]